// this is our main file; it functionally replaces index.html

import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

// my components
import Hello from '@/components/Hello';
import NewConcept from '@/components/NewConcept';
// @ is the project root (see: jsonfig.json), so we don't have to write long annoying import paths


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Hello />
          <NewConcept concept="creating and using components" />
          <NewConcept concept="destructuring objects" />
          <NewConcept concept="next.js and what it bundles & does" />     
        </main>
      </div>
    </>
  );
}
