import { useState } from 'react';

import { MOVIE_LIST } from '../utils/movies'

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Alert from '@mui/material/Alert';
import Button from '@mui/material/Button';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import TextField from '@mui/material/TextField';
import Typography from '@mui/material/Typography';

import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemText from '@mui/material/ListItemText';

// NOTE: This is using old MUI syntax, just so you're exposed to both syntax styles
// in case you end up working in React on the job.

export default function Home() {

  const [searchTitle, setSearchTitle] = useState("");
  const [searchYear, setSearchYear] = useState("");

  // this is what I'll be mutating / rendering from so that the original MOVIE_LIST
  // always remains intact.
  const [movies, setMovies] = useState(MOVIE_LIST);

  const handleSubmit = () => {
    event.preventDefault();
    filterMovies();
    console.log(searchTitle);
    console.log(searchYear);
  }

  const filterMovies = () => {
    // 1. temporarily copy the original MOVIE_LIST so I don't mutate original data
    let filteredMovies = [...MOVIE_LIST] // I can't just = MOVIE_LIST because then it'll alter the original

    // 2. deal with title (trim, lowercase, match on .includes() )
    if (searchTitle.trim()) {
      filteredMovies = filteredMovies.filter(
        (movie) => { 
          // filter's callback function should return something truthy or falsey
          return movie.name.toLowerCase().includes(
            searchTitle.trim().toLowerCase()
          )
        }
      )
    }

    // 3. deal with the year (trim, convert to integter, match on equality)
    if (searchYear.trim()) {
      filteredMovies = filteredMovies.filter((movie) => {
        return movie.year === parseInt(searchYear.trim())
      })
    }

    // 4. now that we're done processing the array, write it to state
    setMovies(filteredMovies);
  }

  return (
    <div>
      <Head>
        <title>Our Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>

      <main>
        <Container>
          <Typography variant="h2" component="h2" style={{textAlign: "center"}}>
            Movies
          </Typography>
          <form
            style={{width: '100%'}}
            onSubmit={handleSubmit}
          >
            <Grid container spacing={2}>
              <Grid item xs={6}>
                <TextField
                  id="search-field"
                  label="search..."
                  variant="standard"
                  value={searchTitle}
                  onChange={(e) => {setSearchTitle(e.target.value)}}
                  sx={{width: '100%'}}
                  
                />
              </Grid>
              <Grid item xs={4}>
                <TextField
                  id="year-field"
                  label="year"
                  variant="standard"
                  value={searchYear}
                  onChange={(e) => {setSearchYear(e.target.value)}}
                  sx={{width: '100%'}}
                 
                />
              </Grid>
              <Grid item xs={2}>
                <Button
                  type="submit"
                  variant="contained"
                >Filter</Button>
              </Grid>
              <Grid item xs={10}>
                {/* Add the error message here*/}
              </Grid>
            </Grid>
          </form>
          <List sx={{width: `100%`}}>
          { movies.map((movieData, index)=> {
              return <ListItem key={index}>
                <ListItemText>
                  <Typography variant="p" component="div">
                    {movieData.name} ({movieData.year})
                  </Typography>
                </ListItemText>
              </ListItem>
            })
          }
          </List>
        </Container>
      </main>
    </div>
  )
}
